import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Register from "./auth/register";
import HeroSection from "../components/screens/main/HeroSection";
import Login from "./auth/login";
import Shops from "../components/screens/main/Shops";
import TrackNumber from "../components/shared/TrackNumber";
import Mission from "../components/screens/main/Mission";
import AboutUs from "../components/screens/main/AboutUs";
import StepWork from "../components/screens/main/StepWork";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Oway USA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <HeroSection/>
        <Shops/>
        <TrackNumber/>
        <Mission/>
        <AboutUs/>
        <StepWork/>
      <main>hello world</main>
    </>
  );
}
